[profile.default]
solc_version = "0.8.26"
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
push_testnet = "https://evm.donut.rpc.push.org/"
sepolia      = "https://ethereum-sepolia-rpc.publicnode.com"
